---

all:
  children:
    edge_nodes:
      hosts:
        edge01:
          network_address: "10.0.1.5"
          ansible_host: "10.0.1.5"
          consul_node_role: server
          network_interface: eth0
          node_kind: metal
          consul_template_release: "consul-template_{{ consul_template_version }}_linux_amd64"
    nomad_cluster:
      hosts:
        server01:
          network_address: "10.0.1.10"
          ansible_host: "10.0.1.10"
          nomad_node_role: both
          consul_node_role: server
          network_interface: eth0
          disk: sda
          node_kind: metal
          nomad_node_class: linux
          nomad_meta:
            PUID: "1000"
            GUID: "1000"
        server02:
          network_address: "10.0.1.11"
          ansible_host: "10.0.1.11"
          nomad_node_role: both
          consul_node_role: server
          network_interface: eth0
          node_kind: metal
          nomad_node_class: linux
          nomad_meta:
            PUID: "1000"
            GUID: "1000"
        client01:
          network_address: "10.0.1.20"
          ansible_host: "10.0.1.20"
          node_kind: nas
          consul_node_role: server
          nomad_node_role: client
          disk: sda
          network_interface: eth0
          nomad_node_class: linux
          nomad_meta:
            is_nas: true
            PUID: "1000"
            GUID: "1000"
        client02:
          network_address: "10.0.1.21"
          ansible_host: "10.0.1.21"
          node_kind: nas
          consul_node_role: client
          nomad_node_role: client
          disk: sda
          network_interface: eth0
          nomad_node_class: linux
          nomad_meta:
            is_nas: true
            PUID: "1000"
            GUID: "1000" 